import React from 'react';
import DetectorForm from '../components/DetectorForm';
import OutputBox from '../components/OutputBox';
import History from '../components/History';

export default function DetectorPage({
  input, setInput, isProcessing, onDetect, onReset, aiScore, aiBreakdown, history, setDetectorInput
}) {
  return (
    <section className="max-w-3xl mx-auto animate-fade-in">
      <div className="text-center mb-10">
        <h2 className="text-3xl md:text-4xl font-bold mb-2 flex items-center justify-center gap-2">
          <svg className="w-7 h-7 text-blue-400" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          Detector
        </h2>
        <p className="text-gray-300 max-w-xl mx-auto">Analyze any text to determine the likelihood it was generated by an AI model. <span className="inline-block bg-blue-900/40 rounded px-2 py-0.5 ml-1 text-xs text-blue-200">New: History & Modern UI</span></p>
      </div>
      <DetectorForm
        input={input}
        setInput={setInput}
        isProcessing={isProcessing}
        onDetect={onDetect}
        onReset={onReset}
      />
      <OutputBox type="detector" aiScore={aiScore} aiBreakdown={aiBreakdown} />
      <History items={history} type="detector" setDetectorInput={setDetectorInput} />
    </section>
  );
} 